In [12]:
import sqlite3
import pandas as pd

In [13]:
con=sqlite3.connect("../data/raw/ipl.db")
def query(sql):
    return pd.read_sql(sql,con)

In [14]:
query('SELECT COUNT(*) AS total_matches FROM matches;')

   total_matches
0           1212

In [15]:
query('''
SELECT DISTINCT season
FROM matches;
''')

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [16]:
query('''
SELECT DISTINCT match_id
FROM deliveries;
''')

      match_id
0       335982
1       335983
2       335984
3       335985
4       335986
...        ...
1207   1529282
1208   1529283
1209   1529284
1210   1529285
1211   1529286

[1212 rows x 1 columns]

In [17]:
query('''
SELECT DISTINCT bowler_type
FROM deliveries;
''')

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [18]:
query('''
SELECT match_id,season,match_winner
FROM matches
WHERE match_winner ='Mumbai Indians';
''')

     match_id season    match_winner
0     1082597   2017  Mumbai Indians
1     1082600   2017  Mumbai Indians
2     1082602   2017  Mumbai Indians
3     1082606   2017  Mumbai Indians
4     1082612   2017  Mumbai Indians
..        ...    ...             ...
150   1473487   2025  Mumbai Indians
151   1473501   2025  Mumbai Indians
152   1473509   2025  Mumbai Indians
153   1527675   2026  Mumbai Indians
154   1529273   2026  Mumbai Indians

[155 rows x 3 columns]

In [19]:
query('''
SELECT match_id,match_date,venue,match_winner
FROM matches
WHERE season ='2018';
''')

,match_id,match_date,venue,match_winner
0,1136561,2018-04-07,Wankhede Stadium,Chennai Super Kings
1,1136562,2018-04-08,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
2,1136563,2018-04-08,Eden Gardens,Kolkata Knight Riders
3,1136564,2018-04-09,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
4,1136565,2018-04-10,MA Chidambaram Stadium,Chennai Super Kings
5,1136566,2018-04-11,Sawai Mansingh Stadium,Rajasthan Royals
6,1136567,2018-04-12,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
7,1136568,2018-04-13,M.Chinnaswamy Stadium,Royal Challengers Bangalore
8,1136569,2018-04-14,Wankhede Stadium,Delhi Capitals
9,1136570,2018-04-14,Eden Gardens,Sunrisers Hyderabad
10,1136571,2018-04-15,M.Chinnaswamy Stadium,Rajasthan Royals
11,1136572,2018-04-15,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
12,1136573,2018-04-16,Eden Gardens,Kolkata Knight Riders
13,1136574,2018-04-17,Wankhede Stadium,Mumbai Indians
14,1136575,2018-04-18,Sawai Mansingh Stadium,Kolkata Knight Riders
15,1136576,2018-04-19,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
16,1136577,2018-04-20,Maharashtra Cricket Association Stadium,Chennai Super Kings
17,1136578,2018-04-21,Eden Gardens,Punjab Kings
18,1136579,2018-04-21,M.Chinnaswamy Stadium,Royal Challengers Bangalore
19,1136580,2018-04-22,Rajiv Gandhi International Stadium,Chennai Super Kings
20,1136581,2018-04-22,Sawai Mansingh Stadium,Rajasthan Royals
21,1136582,2018-04-23,Arun Jaitley Stadium,Punjab Kings
22,1136583,2018-04-24,Wankhede Stadium,Sunrisers Hyderabad
23,1136584,2018-04-25,M.Chinnaswamy Stadium,Chennai Super Kings
24,1136585,2018-04-26,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
25,1136586,2018-04-27,Arun Jaitley Stadium,Delhi Capitals
26,1136587,2018-04-28,Maharashtra Cricket Association Stadium,Mumbai Indians
27,1136588,2018-04-29,Sawai Mansingh Stadium,Sunrisers Hyderabad
28,1136589,2018-04-29,M.Chinnaswamy Stadium,Kolkata Knight Riders
29,1136590,2018-04-30,Maharashtra Cricket Association Stadium,Chennai Super Kings
30,1136591,2018-05-01,M.Chinnaswamy Stadium,Royal Challengers Bangalore
31,1136592,2018-05-02,Arun Jaitley Stadium,Delhi Capitals
32,1136593,2018-05-03,Eden Gardens,Kolkata Knight Riders
33,1136594,2018-05-04,Holkar Cricket Stadium,Mumbai Indians
34,1136595,2018-05-05,Maharashtra Cricket Association Stadium,Chennai Super Kings
35,1136596,2018-05-05,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
36,1136597,2018-05-06,Wankhede Stadium,Mumbai Indians
37,1136598,2018-05-06,Holkar Cricket Stadium,Punjab Kings
38,1136599,2018-05-07,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
39,1136600,2018-05-08,Sawai Mansingh Stadium,Rajasthan Royals
40,1136601,2018-05-09,Eden Gardens,Mumbai Indians
41,1136602,2018-05-10,Arun Jaitley Stadium,Sunrisers Hyderabad
42,1136603,2018-05-11,Sawai Mansingh Stadium,Rajasthan Royals
43,1136604,2018-05-12,Holkar Cricket Stadium,Kolkata Knight Riders
44,1136605,2018-05-12,Arun Jaitley Stadium,Royal Challengers Bangalore
45,1136606,2018-05-13,Maharashtra Cricket Association Stadium,Chennai Super Kings
46,1136607,2018-05-13,Wankhede Stadium,Rajasthan Royals
47,1136608,2018-05-14,Holkar Cricket Stadium,Royal Challengers Bangalore
48,1136609,2018-05-15,Eden Gardens,Kolkata Knight Riders
49,1136610,2018-05-16,Wankhede Stadium,Mumbai Indians
50,1136611,2018-05-17,M.Chinnaswamy Stadium,Royal Challengers Bangalore
51,1136612,2018-05-18,Arun Jaitley Stadium,Delhi Capitals
52,1136613,2018-05-19,Sawai Mansingh Stadium,Rajasthan Royals
53,1136614,2018-05-19,Rajiv Gandhi International Stadium,Kolkata Knight Riders
54,1136615,2018-05-20,Arun Jaitley Stadium,Delhi Capitals
55,1136616,2018-05-20,Maharashtra Cricket Association Stadium,Chennai Super Kings
56,1136617,2018-05-22,Wankhede Stadium,Chennai Super Kings
57,1136618,2018-05-23,Eden Gardens,Kolkata Knight Riders
58,1136619,2018-05-25,Eden Gardens,Sunrisers Hyderabad
59,1136620,2018-05-27,Wankhede Stadium,Chennai Super Kings

In [20]:
query('''
SELECT match_id,season,venue,city
FROM matches
WHERE city ='Mumbai';
''')

     match_id season                     venue    city
0     1082597   2017          Wankhede Stadium  Mumbai
1     1082600   2017          Wankhede Stadium  Mumbai
2     1082606   2017          Wankhede Stadium  Mumbai
3     1082614   2017          Wankhede Stadium  Mumbai
4     1082618   2017          Wankhede Stadium  Mumbai
..        ...    ...                       ...     ...
180   1527675   2026  Wankhede Stadium, Mumbai  Mumbai
181   1527693   2026  Wankhede Stadium, Mumbai  Mumbai
182   1529267   2026  Wankhede Stadium, Mumbai  Mumbai
183   1529276   2026  Wankhede Stadium, Mumbai  Mumbai
184   1529284   2026  Wankhede Stadium, Mumbai  Mumbai

[185 rows x 4 columns]

In [21]:
query('''
SELECT match_id,season,venue,match_winner,win_by_runs
FROM matches
WHERE win_by_runs>=150;
''')

Empty DataFrame
Columns: [match_id, season, venue, match_winner, win_by_runs]
Index: []

In [22]:
query('''
SELECT match_id,season,venue,team1,team2
FROM matches
WHERE match_winner IS NULL;
''')

Empty DataFrame
Columns: [match_id, season, venue, team1, team2]
Index: []

In [23]:
query('''
SELECT match_id,venue,match_winner
FROM matches
ORDER BY match_date DESC
LIMIT 10;
''')

,match_id,venue,match_winner
0,1529286,"Sawai Mansingh Stadium, Jaipur",Delhi Capitals
1,1529285,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans
2,1529284,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad
3,1529283,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals
4,1529282,"Arun Jaitley Stadium, Delhi",Royal Challengers Bangalore
5,1529280,"MA Chidambaram Stadium, Chepauk, Chennai",Gujarat Titans
6,1529281,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants
7,1529278,"Arun Jaitley Stadium, Delhi",Punjab Kings
8,1529279,"Sawai Mansingh Stadium, Jaipur",Sunrisers Hyderabad
9,1529277,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore

In [24]:
query('''
SELECT DISTINCT d.batter
FROM deliveries AS d 
LEFT JOIN players p
ON p.player_name =d.batter
WHERE player_name IS NULL
''')

Empty DataFrame
Columns: [batter]
Index: []

In [25]:
query('''
SELECT m.match_id,m.venue,v.city
FROM matches m
JOIN venues v ON v.venue=m.venue
LIMIT 10;
''')

   match_id                                      venue       city
0    335982                      M Chinnaswamy Stadium  Bangalore
1   1082591  Rajiv Gandhi International Stadium, Uppal  Hyderabad
2   1082592    Maharashtra Cricket Association Stadium       Pune
3   1082593     Saurashtra Cricket Association Stadium     Rajkot
4   1082594                     Holkar Cricket Stadium     Indore
5   1082595                      M.Chinnaswamy Stadium  Bengaluru
6   1082596  Rajiv Gandhi International Stadium, Uppal  Hyderabad
7   1082597                           Wankhede Stadium     Mumbai
8   1082598                     Holkar Cricket Stadium     Indore
9   1082599    Maharashtra Cricket Association Stadium       Pune

In [26]:
query('''
SELECT m.match_id,m.venue
FROM matches m
LEFT JOIN venues v ON v.venue=m.venue
WHERE v.venue IS NULL;
''')

Empty DataFrame
Columns: [match_id, venue]
Index: []

In [27]:
query('''
SELECT bowler_type,LENGTH(bowler_type) AS chars, COUNT(*) AS n
FROM deliveries
GROUP BY bowler_type
ORDER BY chars
LIMIT 5;
''')

      bowler_type  chars      n
0             NaN    NaN    339
1                    1.0      8
2        Legbreak    8.0  13893
3   Left arm Fast   13.0   3727
4  Right arm Fast   14.0  42126

In [28]:
query('''
SELECT match_id,city,
       CASE WHEN city IS NULL THEN 1 ELSE 0 END AS city_missing
FROM matches 
LIMIT 10;
''')

   match_id       city  city_missing
0    335982  Bangalore             0
1   1082591  Hyderabad             0
2   1082592       Pune             0
3   1082593     Rajkot             0
4   1082594     Indore             0
5   1082595  Bengaluru             0
6   1082596  Hyderabad             0
7   1082597     Mumbai             0
8   1082598     Indore             0
9   1082599       Pune             0

In [29]:
query('''
SELECT match_id,city,
       SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS city_missing
FROM matches 
LIMIT 10;
''')

   match_id       city  city_missing
0    335982  Bangalore            51

In [30]:
query('''
SELECT venue FROM venues
EXCEPT
SELECT DISTINCT venue FROM matches;
''')

Empty DataFrame
Columns: [venue]
Index: []

In [31]:
query('''
SELECT COUNT(*) AS total_matches
FROM matches
WHERE season = 2019;
''')

   total_matches
0             60

In [32]:
query('''
SELECT COUNT(DISTINCT bowler) 
FROM deliveries;
''')

   COUNT(DISTINCT bowler)
0                     568

In [33]:
query('''
SELECT venue, COUNT(*) n
FROM matches
GROUP BY venue
ORDER BY n DESC
LIMIT 5;
''')

                      venue   n
0              Eden Gardens  77
1          Wankhede Stadium  73
2     M Chinnaswamy Stadium  65
3          Feroz Shah Kotla  60
4  Wankhede Stadium, Mumbai  57

DATA PROFILING

In [34]:
query('''
SELECT  COUNT(*)                 AS  total_rows,
        COUNT(DISTINCT match_id)  AS  distinct_matches,
        COUNT(DISTINCT ball_number) AS   distinct_balls
FROM deliveries;
''')

   total_rows  distinct_matches  distinct_balls
0      288226              1212              11

In [35]:
query('''

   SELECT match_id,innings,over_number,ball_number,COUNT(*)  AS n
   FROM deliveries
   GROUP BY match_id,innings,over_number,ball_number
   HAVING COUNT(*)> 1;
''')

Empty DataFrame
Columns: [match_id, innings, over_number, ball_number, n]
Index: []

In [36]:
query('''

SELECT COUNT(*) AS total,
   SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END) AS MISSING
FROM matches;
''')

   total  MISSING
0   1212       51

In [37]:
query('''

   SELECT COUNT(*) AS total,
       SUM (CASE WHEN city IS NULL OR TRIM(city) = '' THEN 1 ELSE 0 END ) AS missing
   FROM venues;
''')

   total  missing
0     63        2

In [38]:
query('''
 SELECT COUNT (*) FROM matches;
 
''')

   COUNT (*)
0       1212

In [39]:
query('''
 SELECT COUNT (*) FROM  deliveries;
 
''')

   COUNT (*)
0     288226

In [40]:
query('''
 SELECT COUNT (*) FROM  players;
 
''')

   COUNT (*)
0        799

In [41]:
query('''
 SELECT COUNT (*) FROM  teams;
 
''')

   COUNT (*)
0         16

In [42]:
query('''
 SELECT COUNT (*) FROM  deliveries;
 
''')

   COUNT (*)
0     288226

In [43]:
query('''
 SELECT COUNT (*) FROM  venues;
 
''')

   COUNT (*)
0         63

In [44]:
query('''
SELECT COUNT(DISTINCT season)  AS seasons,
        COUNT(DISTINCT venue)   AS venues,
        COUNT(DISTINCT city)     AS cities,
        COUNT(DISTINCT match_winner) AS winners,
        COUNT(DISTINCT toss_decision)  AS toss_decisions
FROM matches;
  
''')

   seasons  venues  cities  winners  toss_decisions
0       19      59      37       14               2

In [45]:
query('''
      SELECT DISTINCT match_winner FROM matches 
      EXCEPT 
      SELECT team_name FROM  teams;

 
''')

Empty DataFrame
Columns: [match_winner]
Index: []

In [46]:
query('''
  SELECT COUNT(*) AS total,
         SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END )      AS nulls,
         SUM(CASE WHEN city  = '' THEN 1 ELSE 0 END )        AS empties,
         SUM(CASE WHEN TRIM(city) = '' AND city <> '' 
                  THEN 1 ELSE 0 END )                         AS spaces
  FROM matches;
''')

   total  nulls  empties  spaces
0   1212     51        0       0

In [47]:
query('''SELECT COUNT(DISTINCT venue) AS distinct_names FROM matches;''')

   distinct_names
0              59

In [48]:
query('''
 SELECT DISTINCT venue
 FROM matches
 ORDER BY venue;
''')

                                                venue
0                                Arun Jaitley Stadium
1                         Arun Jaitley Stadium, Delhi
2                                    Barabati Stadium
3                 Barsapara Cricket Stadium, Guwahati
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
5                                   Brabourne Stadium
6                           Brabourne Stadium, Mumbai
7                                        Buffalo Park
8                               De Beers Diamond Oval
9                          Dr DY Patil Sports Academy
10                 Dr DY Patil Sports Academy, Mumbai
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
13                Dubai International Cricket Stadium
14                                       Eden Gardens
15                              Eden Gardens, Kolkata
16                                   Feroz Shah Kotla
17                                         Green Park
18       Himachal Pradesh Cricket Association Stadium
19  Himachal Pradesh Cricket Association Stadium, ...
20                             Holkar Cricket Stadium
21                 JSCA International Stadium Complex
22                                          Kingsmead
23                              M Chinnaswamy Stadium
24                   M Chinnaswamy Stadium, Bengaluru
25                              M.Chinnaswamy Stadium
26                             MA Chidambaram Stadium
27                    MA Chidambaram Stadium, Chepauk
28           MA Chidambaram Stadium, Chepauk, Chennai
29  Maharaja Yadavindra Singh International Cricke...
30  Maharaja Yadavindra Singh International Cricke...
31            Maharashtra Cricket Association Stadium
32      Maharashtra Cricket Association Stadium, Pune
33                   Narendra Modi Stadium, Ahmedabad
34                                      Nehru Stadium
35                              New Wanderers Stadium
36                                           Newlands
37                                    OUTsurance Oval
38       Punjab Cricket Association IS Bindra Stadium
39  Punjab Cricket Association IS Bindra Stadium, ...
40  Punjab Cricket Association IS Bindra Stadium, ...
41         Punjab Cricket Association Stadium, Mohali
42                 Rajiv Gandhi International Stadium
43          Rajiv Gandhi International Stadium, Uppal
44  Rajiv Gandhi International Stadium, Uppal, Hyd...
45                       Sardar Patel Stadium, Motera
46             Saurashtra Cricket Association Stadium
47                             Sawai Mansingh Stadium
48                     Sawai Mansingh Stadium, Jaipur
49   Shaheed Veer Narayan Singh International Stadium
50                            Sharjah Cricket Stadium
51                               Sheikh Zayed Stadium
52                                   St George's Park
53                         Subrata Roy Sahara Stadium
54                                    SuperSport Park
55       Vidarbha Cricket Association Stadium, Jamtha
56                                   Wankhede Stadium
57                           Wankhede Stadium, Mumbai
58                   Zayed Cricket Stadium, Abu Dhabi

In [49]:
query('''
  SELECT venue, COUNT(*) AS matches_hosted
  FROM matches
  GROUP BY venue
  ORDER BY venue;
''')

                                                venue  matches_hosted
0                                Arun Jaitley Stadium              14
1                         Arun Jaitley Stadium, Delhi              27
2                                    Barabati Stadium               7
3                 Barsapara Cricket Stadium, Guwahati               8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...              26
5                                   Brabourne Stadium              10
6                           Brabourne Stadium, Mumbai              17
7                                        Buffalo Park               3
8                               De Beers Diamond Oval               3
9                          Dr DY Patil Sports Academy              17
10                 Dr DY Patil Sports Academy, Mumbai              20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...               4
13                Dubai International Cricket Stadium              46
14                                       Eden Gardens              77
15                              Eden Gardens, Kolkata              27
16                                   Feroz Shah Kotla              60
17                                         Green Park               4
18       Himachal Pradesh Cricket Association Stadium               9
19  Himachal Pradesh Cricket Association Stadium, ...               6
20                             Holkar Cricket Stadium               9
21                 JSCA International Stadium Complex               7
22                                          Kingsmead              15
23                              M Chinnaswamy Stadium              65
24                   M Chinnaswamy Stadium, Bengaluru              24
25                              M.Chinnaswamy Stadium              15
26                             MA Chidambaram Stadium               9
27                    MA Chidambaram Stadium, Chepauk              48
28           MA Chidambaram Stadium, Chepauk, Chennai              38
29  Maharaja Yadavindra Singh International Cricke...              10
30  Maharaja Yadavindra Singh International Cricke...               5
31            Maharashtra Cricket Association Stadium              22
32      Maharashtra Cricket Association Stadium, Pune              13
33                   Narendra Modi Stadium, Ahmedabad              37
34                                      Nehru Stadium               5
35                              New Wanderers Stadium               8
36                                           Newlands               7
37                                    OUTsurance Oval               2
38       Punjab Cricket Association IS Bindra Stadium              10
39  Punjab Cricket Association IS Bindra Stadium, ...              11
40  Punjab Cricket Association IS Bindra Stadium, ...               5
41         Punjab Cricket Association Stadium, Mohali              35
42                 Rajiv Gandhi International Stadium              15
43          Rajiv Gandhi International Stadium, Uppal              49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...              23
45                       Sardar Patel Stadium, Motera              12
46             Saurashtra Cricket Association Stadium              10
47                             Sawai Mansingh Stadium              47
48                     Sawai Mansingh Stadium, Jaipur              19
49   Shaheed Veer Narayan Singh International Stadium               6
50                            Sharjah Cricket Stadium              28
51                               Sheikh Zayed Stadium              29
52                                   St George's Park               7
53                         Subrata Roy Sahara Stadium              16
54                                    SuperSport Park              12
55       Vidarbha Cricket Association Stadium, Jamtha               3
56                                   Wankhede Stadium              73
57                           Wankhede Stadium, Mumbai              57
58                   Zayed Cricket Stadium, Abu Dhabi               8

In [50]:
query('''SELECT COUNT(DISTINCT
                 CASE WHEN INSTR(venue,',')>0
                      THEN TRIM(SUBSTR(venue,1,INSTR(venue,',')-1))
                      ELSE TRIM(venue)END) AS after_comma_rule
FROM matches;''')

   after_comma_rule
0                42

In [51]:
query("""SELECT COUNT(*) AS rows_table,
                COUNT(DISTINCT venue) AS distinct_names
         FROM venues;
                
""")

   rows_table  distinct_names
0          63              59

In [52]:
query("""SELECT venue FROM venues
         EXCEPT 
         SELECT DISTINCT venue 
        
FROM matches;""")

Empty DataFrame
Columns: [venue]
Index: []

In [53]:
query("""SELECT  DISTINCT venue FROM matches
         EXCEPT
         SELECT venue
    
                 
FROM venues;""")

Empty DataFrame
Columns: [venue]
Index: []

In [54]:
query("""SELECT VENUE, COUNT(*) AS n
         FROM   venues
         GROUP BY venue
         HAVING COUNT(*) >1; """)

                                               venue  n
0                 Dr DY Patil Sports Academy, Mumbai  2
1                Dubai International Cricket Stadium  2
2  Maharaja Yadavindra Singh International Cricke...  2
3                            Sharjah Cricket Stadium  2

In [55]:
query("""SELECT COUNT(*) 
                
FROM matches;""")

   COUNT(*)
0      1212

In [56]:
query("""SELECT COUNT(*)
                 
FROM matches m  JOIN venues v  ON v.venue=m.venue;""")

   COUNT(*)
0      1316

In [57]:
query("""SELECT team_name,
                (SELECT COUNT(*) FROM matches m
                 WHERE m.team1=t.team_name OR m.team2 =t.team_name) AS played
FROM teams t
ORDER BY played;""")

                      team_name  played
0               Deccan Chargers       0
1       Rising Pune Supergiants       0
2          Kochi Tuskers Kerala      14
3        Rising Pune Supergiant      30
4                 Gujarat Lions      30
5                 Pune Warriors      46
6          Lucknow Super Giants      66
7                Gujarat Titans      69
8              Rajasthan Royals     245
9           Chennai Super Kings     260
10        Kolkata Knight Riders     272
11                 Punjab Kings     272
12               Delhi Capitals     276
13  Royal Challengers Bangalore     279
14          Sunrisers Hyderabad     280
15               Mumbai Indians     285

In [58]:
query("""SELECT team1 AS  team , season FROM matches WHERE team1 LIKE 'Gujarat%'
         UNION 
          SELECT team2, season FROM matches WHERE team2 LIKE 'Gujarat%'  
           ORDER BY team,season; """)

             team season
0   Gujarat Lions   2016
1   Gujarat Lions   2017
2  Gujarat Titans   2022
3  Gujarat Titans   2023
4  Gujarat Titans   2024
5  Gujarat Titans   2025
6  Gujarat Titans   2026

In [59]:
query("""SELECT bowler_type ,LENGTH(bowler_type) AS chars,COUNT(*) AS n
FROM deliveries
GROUP BY bowler_type
ORDER BY  chars 
LIMIT 5;""")

      bowler_type  chars      n
0             NaN    NaN    339
1                    1.0      8
2        Legbreak    8.0  13893
3   Left arm Fast   13.0   3727
4  Right arm Fast   14.0  42126

In [60]:
query("""SELECT field_pos ,LENGTH(field_pos) AS chars,COUNT(*) AS n
FROM players
GROUP BY field_pos
ORDER BY  chars 
LIMIT 5;""")

          field_pos  chars    n
0               NaN    NaN   88
1                      1.0  612
2      Wicketkeeper   12.0   82
3    Right arm Fast   14.0    1
4  Right arm Medium   16.0    1

In [61]:
query("""SELECT LOWER(TRIM(bowler_type)) AS folded,
                 COUNT(DISTINCT bowler_type) AS spellings
FROM deliveries
WHERE bowler_type IS NOT NULL
GROUP BY folded
HAVING COUNT(DISTINCT bowler_type) > 1;""")

                  folded  spellings
0  right arm fast medium          2

In [62]:
query("""SELECT result, COUNT(*) AS n FROM matches GROUP BY result;""")

      result     n
0  no result     9
1        tie    16
2        win  1187

In [63]:
query("""SELECT match_id, season, result, match_winner
FROM matches
WHERE result = 'no result' AND match_winner <> '';""")

   match_id season     result           match_winner
0   1178424   2019  no result       Rajasthan Royals
1   1359519   2023  no result    Chennai Super Kings
2    501265   2011  no result          Pune Warriors
3    829763   2015  no result       Rajasthan Royals
4    829813   2015  no result         Delhi Capitals
5   1473481   2025  no result  Kolkata Knight Riders
6   1473492   2025  no result    Sunrisers Hyderabad
7   1473495   2025  no result         Delhi Capitals
8   1527685   2026  no result           Punjab Kings

In [64]:
query("""SELECT match_winner, COUNT(*) AS wins FROM matches
GROUP BY match_winner ORDER BY wins DESC LIMIT 3;""")

                  match_winner  wins
0               Mumbai Indians   155
1          Chennai Super Kings   146
2  Royal Challengers Bangalore   139

In [65]:
query("""SELECT match_winner, COUNT(*) AS wins FROM matches
WHERE result = 'win'
GROUP BY match_winner ORDER BY wins DESC LIMIT 3;""")

                  match_winner  wins
0               Mumbai Indians   153
1          Chennai Super Kings   145
2  Royal Challengers Bangalore   138