In [4]:
import pandas as pd 
import sqlite3
con=sqlite3.connect('../data/raw/ipl.db')
def q(sql):
    return pd.read_sql(sql,con)

In [5]:
q("""
SELECT bowler_type
FROM deliveries;
""")

             bowler_type
0       Right arm Medium
1       Right arm Medium
2       Right arm Medium
3       Right arm Medium
4       Right arm Medium
...                  ...
288221    Right arm Fast
288222    Right arm Fast
288223    Right arm Fast
288224  Right arm Medium
288225  Right arm Medium

[288226 rows x 1 columns]

find

In [6]:
q("""
SELECT bowler_type ,LENGTH(bowler_type) AS len,COUNT(*) AS rows
FROM deliveries
GROUP BY bowler_type
ORDER BY len
LIMIT 5;
""")

      bowler_type   len   rows
0             NaN   NaN    339
1                   1.0      8
2        Legbreak   8.0  13893
3   Left arm Fast  13.0   3727
4  Right arm Fast  14.0  42126

fx

In [7]:
q("""
SELECT bowler_type,LENGTH(bowler_type) AS old_length,NULLIF(TRIM(bowler_type),'') AS bowler_type_clean
FROM deliveries
WHERE TRIM (bowler_type)='';
""")

  bowler_type  old_length bowler_type_clean
0                       1              None
1                       1              None
2                       1              None
3                       1              None
4                       1              None
5                       1              None
6                       1              None
7                       1              None

verify

In [8]:
q("""
SELECT COUNT(*) AS whitespaces_only
FROM 
(SELECT NULLIF(TRIM(bowler_type),'') AS bowler_type FROM deliveries)
WHERE bowler_type IS NOT NULL AND TRIM(bowler_type)='';
""")

   whitespaces_only
0                 0

In [9]:
q("""
SELECT COUNT(*) AS unknown_bowler_type
FROM deliveries
WHERE NULLIF(TRIM(bowler_type),'') IS NULL;""")

   unknown_bowler_type
0                  347

In [10]:
q("""
SELECT DISTINCT(bowler_type)
FROM deliveries;""")

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [11]:
q("""
SELECT toss_decision,
CASE WHEN toss_decision='bat' THEN 'Batting First'
WHEN toss_decision='field' THEN 'Feilding First'
ELSE toss_decision END AS toss_decision_clean,
COUNT(*)
FROM matches
GROUP BY toss_decision;""")

  toss_decision toss_decision_clean  COUNT(*)
0           bat       Batting First       412
1         field      Feilding First       800

find

In [12]:
q("""
SELECT bowler_type,COUNT(*) AS n
FROM deliveries
GROUP BY bowler_type
ORDER BY bowler_type;""")

                                       bowler_type      n
0                                              NaN    339
1                                                       8
2                                    Left arm Fast   3727
3                             Left arm Fast medium  15376
4                                  Left arm Medium   8778
5                             Left arm Medium fast  13495
6                              Left arm Wrist spin   4279
7                                         Legbreak  13893
8                                  Legbreak Googly  22670
9                                   Right arm Fast  42126
10                           Right arm Fast Medium     73
11                           Right arm Fast medium  31154
12                                Right arm Medium  49776
13                           Right arm Medium fast  20897
14            Right arm Medium, Right arm Offbreak    652
15  Right arm Medium, Right arm Offbreak, Legbreak    223
16                              Right arm Offbreak  30791
17                    Right arm Offbreak, Legbreak    448
18             Right arm Offbreak, Legbreak Googly     61
19      Right arm Offbreak, Slow Left arm Orthodox     42
20                          Slow Left arm Orthodox  29128
21     Slow Left arm Orthodox, Left arm Wrist spin    290

fix

In [13]:
q("""
SELECT bowler_type,
CASE WHEN bowler_type='Right arm Fast Medium' THEN 'Right arm Fast medium'
ELSE bowler_type END AS bowler_type_clean
FROM deliveries;""")

             bowler_type bowler_type_clean
0       Right arm Medium  Right arm Medium
1       Right arm Medium  Right arm Medium
2       Right arm Medium  Right arm Medium
3       Right arm Medium  Right arm Medium
4       Right arm Medium  Right arm Medium
...                  ...               ...
288221    Right arm Fast    Right arm Fast
288222    Right arm Fast    Right arm Fast
288223    Right arm Fast    Right arm Fast
288224  Right arm Medium  Right arm Medium
288225  Right arm Medium  Right arm Medium

[288226 rows x 2 columns]

combine

In [14]:
q("""
SELECT 
CASE WHEN NULLIF(TRIM(bowler_type),'')='Right arm Fast Medium' THEN 'Right  arm Fast medium'
ELSE NULLIF(TRIM(bowler_type),'') END AS bowler_type_clean
FROM deliveries;""")

       bowler_type_clean
0       Right arm Medium
1       Right arm Medium
2       Right arm Medium
3       Right arm Medium
4       Right arm Medium
...                  ...
288221    Right arm Fast
288222    Right arm Fast
288223    Right arm Fast
288224  Right arm Medium
288225  Right arm Medium

[288226 rows x 1 columns]

In [15]:
q("""
SELECT COUNT (DISTINCT bowler_type) AS n
FROM deliveries;""")

    n
0  21

verify

In [16]:
q("""
SELECT COUNT (DISTINCT 
CASE WHEN NULLIF(TRIM(bowler_type),'')='Right arm Fast Medium' THEN 'Right arm Fast medium'
ELSE NULLIF(TRIM(bowler_type),'') END )AS cleaned_count
FROM deliveries;""")

   cleaned_count
0             19

team-team name

find

In [17]:
q("""
SELECT team_name,
(SELECT COUNT(*) FROM matches m
WHERE m.team1=t.team_name OR m.team2=t.team_name) AS played
FROM teams t
ORDER BY played;""")

                      team_name  played
0               Deccan Chargers       0
1       Rising Pune Supergiants       0
2          Kochi Tuskers Kerala      14
3        Rising Pune Supergiant      30
4                 Gujarat Lions      30
5                 Pune Warriors      46
6          Lucknow Super Giants      66
7                Gujarat Titans      69
8              Rajasthan Royals     245
9           Chennai Super Kings     260
10        Kolkata Knight Riders     272
11                 Punjab Kings     272
12               Delhi Capitals     276
13  Royal Challengers Bangalore     279
14          Sunrisers Hyderabad     280
15               Mumbai Indians     285

fix and verified

In [18]:
q("""
SELECT team_name,
CASE WHEN team_name='Rising Pune Supergiants' THEN 'Rising Pune  Supergiant'
ELSE team_name END AS team_name_clean
FROM teams;""")

                      team_name              team_name_clean
0   Royal Challengers Bangalore  Royal Challengers Bangalore
1           Sunrisers Hyderabad          Sunrisers Hyderabad
2                Mumbai Indians               Mumbai Indians
3        Rising Pune Supergiant       Rising Pune Supergiant
4                 Gujarat Lions                Gujarat Lions
5         Kolkata Knight Riders        Kolkata Knight Riders
6           Chennai Super Kings          Chennai Super Kings
7              Rajasthan Royals             Rajasthan Royals
8                Delhi Capitals               Delhi Capitals
9                  Punjab Kings                 Punjab Kings
10         Lucknow Super Giants         Lucknow Super Giants
11               Gujarat Titans               Gujarat Titans
12              Deccan Chargers              Deccan Chargers
13         Kochi Tuskers Kerala         Kochi Tuskers Kerala
14                Pune Warriors                Pune Warriors
15      Rising Pune Supergiants      Rising Pune  Supergiant

In [19]:
q("""
 SELECT INSTR('Wankhede Stadium,Mumbai',',') AS coma_position""")

   coma_position
0             17

In [20]:
q("""
SELECT SUBSTR('Wankhede Stadium,Mumbai',1,17-1) AS extract""")

            extract
0  Wankhede Stadium

In [21]:
q(""" SELECT COUNT (DISTINCT venue) 
FROM venues;""")

   COUNT (DISTINCT venue)
0                      59

In [22]:
q(""" SELECT  DISTINCT venue
FROM venues;""")

                                                venue
0                               M Chinnaswamy Stadium
1           Rajiv Gandhi International Stadium, Uppal
2             Maharashtra Cricket Association Stadium
3              Saurashtra Cricket Association Stadium
4                              Holkar Cricket Stadium
5                               M.Chinnaswamy Stadium
6                                    Wankhede Stadium
7                                        Eden Gardens
8                                    Feroz Shah Kotla
9   Punjab Cricket Association IS Bindra Stadium, ...
10                                         Green Park
11       Punjab Cricket Association IS Bindra Stadium
12                 Rajiv Gandhi International Stadium
13                             MA Chidambaram Stadium
14                             Sawai Mansingh Stadium
15                               Arun Jaitley Stadium
16  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
17                               Sheikh Zayed Stadium
18                Dubai International Cricket Stadium
19                            Sharjah Cricket Stadium
20           MA Chidambaram Stadium, Chepauk, Chennai
21                           Wankhede Stadium, Mumbai
22                   Narendra Modi Stadium, Ahmedabad
23                        Arun Jaitley Stadium, Delhi
24                   Zayed Cricket Stadium, Abu Dhabi
25                          Brabourne Stadium, Mumbai
26                 Dr DY Patil Sports Academy, Mumbai
27      Maharashtra Cricket Association Stadium, Pune
28                              Eden Gardens, Kolkata
29  Punjab Cricket Association IS Bindra Stadium, ...
30  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
31  Rajiv Gandhi International Stadium, Uppal, Hyd...
32                   M Chinnaswamy Stadium, Bengaluru
33                Barsapara Cricket Stadium, Guwahati
34                     Sawai Mansingh Stadium, Jaipur
35  Himachal Pradesh Cricket Association Stadium, ...
36  Maharaja Yadavindra Singh International Cricke...
37  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
38         Punjab Cricket Association Stadium, Mohali
39                    MA Chidambaram Stadium, Chepauk
40                         Dr DY Patil Sports Academy
41                                           Newlands
42                                   St George's Park
43                                          Kingsmead
44                                    SuperSport Park
45                                       Buffalo Park
46                              New Wanderers Stadium
47                              De Beers Diamond Oval
48                                    OUTsurance Oval
49                                  Brabourne Stadium
50                       Sardar Patel Stadium, Motera
51                                   Barabati Stadium
52       Vidarbha Cricket Association Stadium, Jamtha
53       Himachal Pradesh Cricket Association Stadium
54                                      Nehru Stadium
55                         Subrata Roy Sahara Stadium
56   Shaheed Veer Narayan Singh International Stadium
57                 JSCA International Stadium Complex
58  Maharaja Yadavindra Singh International Cricke...

In [23]:
q(""" 
SELECT COUNT(DISTINCT TRIM(SUBSTR(venue, 1,
CASE WHEN INSTR(venue,',') > 0
THEN INSTR(venue,',')-1 ELSE LENGTH(venue)END))) AS after_rule
FROM matches;
""")

   after_rule
0          42

In [24]:
q(""" 
SELECT DISTINCT TRIM(SUBSTR(venue, 1,
CASE WHEN INSTR(venue,',') > 0
THEN INSTR(venue,',')-1 ELSE LENGTH(venue)END)) AS venue_clean
FROM matches;
""")

                                          venue_clean
0                               M Chinnaswamy Stadium
1                  Rajiv Gandhi International Stadium
2             Maharashtra Cricket Association Stadium
3              Saurashtra Cricket Association Stadium
4                              Holkar Cricket Stadium
5                               M.Chinnaswamy Stadium
6                                    Wankhede Stadium
7                                        Eden Gardens
8                                    Feroz Shah Kotla
9        Punjab Cricket Association IS Bindra Stadium
10                                         Green Park
11                             MA Chidambaram Stadium
12                             Sawai Mansingh Stadium
13                               Arun Jaitley Stadium
14  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
15                               Sheikh Zayed Stadium
16                Dubai International Cricket Stadium
17                            Sharjah Cricket Stadium
18                              Narendra Modi Stadium
19                              Zayed Cricket Stadium
20                                  Brabourne Stadium
21                         Dr DY Patil Sports Academy
22  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
23                          Barsapara Cricket Stadium
24       Himachal Pradesh Cricket Association Stadium
25  Maharaja Yadavindra Singh International Cricke...
26                 Punjab Cricket Association Stadium
27                                           Newlands
28                                   St George's Park
29                                          Kingsmead
30                                    SuperSport Park
31                                       Buffalo Park
32                              New Wanderers Stadium
33                              De Beers Diamond Oval
34                                    OUTsurance Oval
35                               Sardar Patel Stadium
36                                   Barabati Stadium
37               Vidarbha Cricket Association Stadium
38                                      Nehru Stadium
39                         Subrata Roy Sahara Stadium
40   Shaheed Veer Narayan Singh International Stadium
41                 JSCA International Stadium Complex

Find

In [25]:
q("""SELECT COUNT(*) AS total, 
SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS missing_city 
FROM matches;  """)

   total  missing_city
0   1212            51

In [39]:
q("""SELECT COALESCE(city, 'UNKNOWN') AS city_filled 
FROM matches; """)

         city_filled
0          Bangalore
1          Hyderabad
2               Pune
3             Rajkot
4             Indore
...              ...
1207           Delhi
1208  New Chandigarh
1209          Mumbai
1210       Ahmedabad
1211          Jaipur

[1212 rows x 1 columns]

In [26]:
q("SELECT COALESCE('KOCHI', 'UNKNOWN');")

  COALESCE('KOCHI', 'UNKNOWN')
0                        KOCHI

In [27]:
q("SELECT COALESCE(NULL, 'UNKNOWN');")

  COALESCE(NULL, 'UNKNOWN')
0                   UNKNOWN

In [28]:
q(""" 
SELECT city,COALESCE(city,'UNKNOWN')
FROM matches
WHERE city IS NULL
LIMIT 10;
""")

   city COALESCE(city,'UNKNOWN')
0  None                  UNKNOWN
1  None                  UNKNOWN
2  None                  UNKNOWN
3  None                  UNKNOWN
4  None                  UNKNOWN
5  None                  UNKNOWN
6  None                  UNKNOWN
7  None                  UNKNOWN
8  None                  UNKNOWN
9  None                  UNKNOWN

In [29]:
q(""" SELECT COUNT(*) AS N
  FROM matches
  WHERE COALESCE (city,'UNKNOWN') = 'UNKNOWN';""")

    N
0  51

In [30]:
q(" SELECT CAST ('2019' AS INTEGER);")

   CAST ('2019' AS INTEGER)
0                      2019

In [31]:
q('''
SELECT DISTINCT season,
SUBSTR(season,1,4)AS first_four,
CAST(SUBSTR(season,1,4)AS INTEGER)AS season_year
FROM matches
ORDER BY season_year;
''')

     season first_four  season_year
0      2008       2008         2008
1      2009       2009         2009
2      2010       2010         2010
3      2011       2011         2011
4      2012       2012         2012
5      2013       2013         2013
6      2014       2014         2014
7      2015       2015         2015
8      2016       2016         2016
9      2017       2017         2017
10     2018       2018         2018
11     2019       2019         2019
12  2020/21       2020         2020
13     2021       2021         2021
14     2022       2022         2022
15     2023       2023         2023
16     2024       2024         2024
17     2025       2025         2025
18     2026       2026         2026

In [32]:
q("""SELECT venue, COUNT(*) AS n
FROM venues
GROUP BY venue;""")

                                                venue  n
0                                Arun Jaitley Stadium  1
1                         Arun Jaitley Stadium, Delhi  1
2                                    Barabati Stadium  1
3                 Barsapara Cricket Stadium, Guwahati  1
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...  1
5                                   Brabourne Stadium  1
6                           Brabourne Stadium, Mumbai  1
7                                        Buffalo Park  1
8                               De Beers Diamond Oval  1
9                          Dr DY Patil Sports Academy  1
10                 Dr DY Patil Sports Academy, Mumbai  2
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...  1
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...  1
13                Dubai International Cricket Stadium  2
14                                       Eden Gardens  1
15                              Eden Gardens, Kolkata  1
16                                   Feroz Shah Kotla  1
17                                         Green Park  1
18       Himachal Pradesh Cricket Association Stadium  1
19  Himachal Pradesh Cricket Association Stadium, ...  1
20                             Holkar Cricket Stadium  1
21                 JSCA International Stadium Complex  1
22                                          Kingsmead  1
23                              M Chinnaswamy Stadium  1
24                   M Chinnaswamy Stadium, Bengaluru  1
25                              M.Chinnaswamy Stadium  1
26                             MA Chidambaram Stadium  1
27                    MA Chidambaram Stadium, Chepauk  1
28           MA Chidambaram Stadium, Chepauk, Chennai  1
29  Maharaja Yadavindra Singh International Cricke...  2
30  Maharaja Yadavindra Singh International Cricke...  1
31            Maharashtra Cricket Association Stadium  1
32      Maharashtra Cricket Association Stadium, Pune  1
33                   Narendra Modi Stadium, Ahmedabad  1
34                                      Nehru Stadium  1
35                              New Wanderers Stadium  1
36                                           Newlands  1
37                                    OUTsurance Oval  1
38       Punjab Cricket Association IS Bindra Stadium  1
39  Punjab Cricket Association IS Bindra Stadium, ...  1
40  Punjab Cricket Association IS Bindra Stadium, ...  1
41         Punjab Cricket Association Stadium, Mohali  1
42                 Rajiv Gandhi International Stadium  1
43          Rajiv Gandhi International Stadium, Uppal  1
44  Rajiv Gandhi International Stadium, Uppal, Hyd...  1
45                       Sardar Patel Stadium, Motera  1
46             Saurashtra Cricket Association Stadium  1
47                             Sawai Mansingh Stadium  1
48                     Sawai Mansingh Stadium, Jaipur  1
49   Shaheed Veer Narayan Singh International Stadium  1
50                            Sharjah Cricket Stadium  2
51                               Sheikh Zayed Stadium  1
52                                   St George's Park  1
53                         Subrata Roy Sahara Stadium  1
54                                    SuperSport Park  1
55       Vidarbha Cricket Association Stadium, Jamtha  1
56                                   Wankhede Stadium  1
57                           Wankhede Stadium, Mumbai  1
58                   Zayed Cricket Stadium, Abu Dhabi  1

In [33]:
q("""
SELECT venue, COUNT(*) 
OVER(PARTITION BY venue)
FROM venues;
""")

,venue,COUNT(*) \nOVER(PARTITION BY venue)
0,Arun Jaitley Stadium,1
1,"Arun Jaitley Stadium, Delhi",1
2,Barabati Stadium,1
3,"Barsapara Cricket Stadium, Guwahati",1
4,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
...,...,...
58,SuperSport Park,1
59,"Vidarbha Cricket Association Stadium, Jamtha",1
60,Wankhede Stadium,1
61,"Wankhede Stadium, Mumbai",1
62,"Zayed Cricket Stadium, Abu Dhabi",1

In [34]:
q("""
SELECT venue_id,venue,
ROW_NUMBER()OVER(PARTITION BY venue ORDER BY venue_id) AS rn
FROM venues;
""")

    venue_id                                              venue  rn
0         16                               Arun Jaitley Stadium   1
1         24                        Arun Jaitley Stadium, Delhi   1
2         55                                   Barabati Stadium   1
3         37                Barsapara Cricket Stadium, Guwahati   1
4         34  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   1
..       ...                                                ...  ..
58        48                                    SuperSport Park   1
59        56       Vidarbha Cricket Association Stadium, Jamtha   1
60         7                                   Wankhede Stadium   1
61        22                           Wankhede Stadium, Mumbai   1
62        25                   Zayed Cricket Stadium, Abu Dhabi   1

[63 rows x 3 columns]

verify

In [35]:
q("""
WITH ranked AS(
SELECT venue_id,venue,
ROW_NUMBER()OVER(PARTITION BY venue ORDER BY venue_id) AS rn
FROM venues)
SELECT COUNT(*) AS kept
FROM ranked
WHERE rn=1;""")

   kept
0    59

CREATE VIEW - to save the query

In [36]:
con.executescript("""
DROP VIEW IF EXISTS v_matches_clean;
CREATE VIEW v_matches_clean AS 
SELECT *,
CASE WHEN venue_comma_clean='M.Chinnaswamy Stadium'THEN 'M Chinnaswamy Stadium' ELSE venue_comma_clean END AS venue_clean
FROM(SELECT *,
TRIM(SUBSTR(venue,1,CASE 
WHEN INSTR(venue,',')>0 
THEN INSTR(venue,',')-1 
ELSE LENGTH(venue)
END)) AS venue_comma_clean
FROM matches); """)
con.commit()

In [37]:
q("""
SELECT COUNT(DISTINCT venue_clean)
FROM v_matches_clean;""")

   COUNT(DISTINCT venue_clean)
0                           41

In [38]:
q("""
SELECT venue_clean,COUNT(*) AS matches_hosted
FROM v_matches_clean
GROUP BY venue_clean
ORDER BY matches_hosted DESC
LIMIT 5;""")

                          venue_clean  matches_hosted
0                    Wankhede Stadium             130
1               M Chinnaswamy Stadium             104
2                        Eden Gardens             104
3              MA Chidambaram Stadium              95
4  Rajiv Gandhi International Stadium              87