In [2]:
import pandas as pd
import sqlite3
con = sqlite3.connect("C:/Users/fathi/Downloads/ipl sem 3/IPL-Cricket-Analyticss/data/raw/ipl.db")
def q(sql):
    return pd.read_sql(sql,con)

In [3]:
q('''
SELECT bowler_type
from deliveries;
''')

             bowler_type
0       Right arm Medium
1       Right arm Medium
2       Right arm Medium
3       Right arm Medium
4       Right arm Medium
...                  ...
288221    Right arm Fast
288222    Right arm Fast
288223    Right arm Fast
288224  Right arm Medium
288225  Right arm Medium

[288226 rows x 1 columns]

Find

In [4]:
q('''
SELECT bowler_type, LENGTH(bowler_type) AS value_length,
COUNT(*) AS count
FROM deliveries
GROUP BY bowler_type
ORDER BY value_length
LIMIT 5;''')

      bowler_type  value_length  count
0             NaN           NaN    339
1                           1.0      8
2        Legbreak           8.0  13893
3   Left arm Fast          13.0   3727
4  Right arm Fast          14.0  42126

FIX

In [5]:
q('''
SELECT bowler_type,LENGTH(bowler_type)AS old_length,NULLIF(TRIM(bowler_type),'')AS bowler_type_clean
from deliveries
where TRIM(bowler_type)='';''')

  bowler_type  old_length bowler_type_clean
0                       1              None
1                       1              None
2                       1              None
3                       1              None
4                       1              None
5                       1              None
6                       1              None
7                       1              None

VERIFY

In [6]:
q('''
SELECT COUNT(*)AS whitespace_only
FROM
(SELECT NULLIF(TRIM(bowler_type),'')AS bowler_type FROM deliveries)
WHERE bowler_type IS NOT NULL AND TRIM(bowler_type)='';
''')

   whitespace_only
0                0

In [7]:
q('''
SELECT COUNT(*)AS unknown_bowler_type
FROM deliveries
WHERE NULLIF(TRIM(bowler_type),'')IS NULL;
''')

   unknown_bowler_type
0                  347

FIND

In [8]:
q('''
SELECT  DISTINCT bowler_type FROM deliveries; ''')

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [9]:
q("""SELECT toss_decision,CASE WHEN toss_decision='bat' THEN 'Batting First' 
WHEN toss_decision='field' THEN 'Fielding First' 
ELSE toss_decision END AS toss_decision_clean,
COUNT(*) AS n
FROM matches
GROUP BY toss_decision;"""
)

  toss_decision toss_decision_clean    n
0           bat       Batting First  412
1         field      Fielding First  800

In [10]:
q('''SELECT bowler_type, COUNT(*) AS count
FROM deliveries
GROUP BY bowler_type
ORDER BY bowler_type;''')

                                       bowler_type  count
0                                              NaN    339
1                                                       8
2                                    Left arm Fast   3727
3                             Left arm Fast medium  15376
4                                  Left arm Medium   8778
5                             Left arm Medium fast  13495
6                              Left arm Wrist spin   4279
7                                         Legbreak  13893
8                                  Legbreak Googly  22670
9                                   Right arm Fast  42126
10                           Right arm Fast Medium     73
11                           Right arm Fast medium  31154
12                                Right arm Medium  49776
13                           Right arm Medium fast  20897
14            Right arm Medium, Right arm Offbreak    652
15  Right arm Medium, Right arm Offbreak, Legbreak    223
16                              Right arm Offbreak  30791
17                    Right arm Offbreak, Legbreak    448
18             Right arm Offbreak, Legbreak Googly     61
19      Right arm Offbreak, Slow Left arm Orthodox     42
20                          Slow Left arm Orthodox  29128
21     Slow Left arm Orthodox, Left arm Wrist spin    290

In [11]:
q('''
SELECT bowler_type,CASE WHEN bowler_type='Right arm Fast Medium' THEN 'Right arm fast medium' ELSE bowler_type END AS bowler_type
FROM deliveries;''')

             bowler_type       bowler_type
0       Right arm Medium  Right arm Medium
1       Right arm Medium  Right arm Medium
2       Right arm Medium  Right arm Medium
3       Right arm Medium  Right arm Medium
4       Right arm Medium  Right arm Medium
...                  ...               ...
288221    Right arm Fast    Right arm Fast
288222    Right arm Fast    Right arm Fast
288223    Right arm Fast    Right arm Fast
288224  Right arm Medium  Right arm Medium
288225  Right arm Medium  Right arm Medium

[288226 rows x 2 columns]

In [12]:
q('''
SELECT CASE WHEN NULLIF(TRIM(bowler_type),'')='Right arm Fast Medium' THEN 'Right arm Fast Medium'
ELSE NULLIF(TRIM(bowler_type),'')
END AS bowler_type_clean
FROM deliveries; ''')

       bowler_type_clean
0       Right arm Medium
1       Right arm Medium
2       Right arm Medium
3       Right arm Medium
4       Right arm Medium
...                  ...
288221    Right arm Fast
288222    Right arm Fast
288223    Right arm Fast
288224  Right arm Medium
288225  Right arm Medium

[288226 rows x 1 columns]

In [13]:
q('''
SELECT COUNT (DISTINCT( bowler_type))
FROM deliveries;
''')

   COUNT (DISTINCT( bowler_type))
0                              21

In [14]:
q('''
SELECT COUNT(DISTINCT
CASE WHEN NULLIF(TRIM(bowler_type),'')='Right arm Fast Medium' THEN 'Right arm Fast medium'
ELSE NULLIF(TRIM(bowler_type),'')END)
AS cleaned_count
FROM deliveries; 
''')

   cleaned_count
0             19

In [15]:
q('''
SELECT team_name,
(SELECT COUNT (*)FROM matches m
WHERE m.team1=t.team_name OR m.team2=t.team_name)AS played
FROM teams t
ORDER BY played;
''')

                      team_name  played
0               Deccan Chargers       0
1       Rising Pune Supergiants       0
2          Kochi Tuskers Kerala      14
3        Rising Pune Supergiant      30
4                 Gujarat Lions      30
5                 Pune Warriors      46
6          Lucknow Super Giants      66
7                Gujarat Titans      69
8              Rajasthan Royals     245
9           Chennai Super Kings     260
10        Kolkata Knight Riders     272
11                 Punjab Kings     272
12               Delhi Capitals     276
13  Royal Challengers Bangalore     279
14          Sunrisers Hyderabad     280
15               Mumbai Indians     285

In [16]:
q('''
SELECT team_name,
CASE WHEN team_name = 'Rising Pune Supergiants' THEN 'Rising Pune Supergiant'
ELSE team_name END as t
FROM teams;
''')

                      team_name                            t
0   Royal Challengers Bangalore  Royal Challengers Bangalore
1           Sunrisers Hyderabad          Sunrisers Hyderabad
2                Mumbai Indians               Mumbai Indians
3        Rising Pune Supergiant       Rising Pune Supergiant
4                 Gujarat Lions                Gujarat Lions
5         Kolkata Knight Riders        Kolkata Knight Riders
6           Chennai Super Kings          Chennai Super Kings
7              Rajasthan Royals             Rajasthan Royals
8                Delhi Capitals               Delhi Capitals
9                  Punjab Kings                 Punjab Kings
10         Lucknow Super Giants         Lucknow Super Giants
11               Gujarat Titans               Gujarat Titans
12              Deccan Chargers              Deccan Chargers
13         Kochi Tuskers Kerala         Kochi Tuskers Kerala
14                Pune Warriors                Pune Warriors
15      Rising Pune Supergiants       Rising Pune Supergiant

In [17]:
q('''
SELECT INSTR('Wankhede Stadium,Mumbai',',');''')

   INSTR('Wankhede Stadium,Mumbai',',')
0                                    17

In [18]:
q("""
SELECT SUBSTR('Wankhede Stadium,Mumbai',1,17-1) AS extract;""")

            extract
0  Wankhede Stadium

In [19]:
q('''
SELECT DISTINCT venue
FROM matches; ''')

                                                venue
0                               M Chinnaswamy Stadium
1           Rajiv Gandhi International Stadium, Uppal
2             Maharashtra Cricket Association Stadium
3              Saurashtra Cricket Association Stadium
4                              Holkar Cricket Stadium
5                               M.Chinnaswamy Stadium
6                                    Wankhede Stadium
7                                        Eden Gardens
8                                    Feroz Shah Kotla
9   Punjab Cricket Association IS Bindra Stadium, ...
10                                         Green Park
11       Punjab Cricket Association IS Bindra Stadium
12                 Rajiv Gandhi International Stadium
13                             MA Chidambaram Stadium
14                             Sawai Mansingh Stadium
15                               Arun Jaitley Stadium
16  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
17                               Sheikh Zayed Stadium
18                Dubai International Cricket Stadium
19                            Sharjah Cricket Stadium
20           MA Chidambaram Stadium, Chepauk, Chennai
21                           Wankhede Stadium, Mumbai
22                   Narendra Modi Stadium, Ahmedabad
23                        Arun Jaitley Stadium, Delhi
24                   Zayed Cricket Stadium, Abu Dhabi
25                          Brabourne Stadium, Mumbai
26                 Dr DY Patil Sports Academy, Mumbai
27      Maharashtra Cricket Association Stadium, Pune
28                              Eden Gardens, Kolkata
29  Punjab Cricket Association IS Bindra Stadium, ...
30  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
31  Rajiv Gandhi International Stadium, Uppal, Hyd...
32                   M Chinnaswamy Stadium, Bengaluru
33                Barsapara Cricket Stadium, Guwahati
34                     Sawai Mansingh Stadium, Jaipur
35  Himachal Pradesh Cricket Association Stadium, ...
36  Maharaja Yadavindra Singh International Cricke...
37  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
38         Punjab Cricket Association Stadium, Mohali
39                    MA Chidambaram Stadium, Chepauk
40                         Dr DY Patil Sports Academy
41                                           Newlands
42                                   St George's Park
43                                          Kingsmead
44                                    SuperSport Park
45                                       Buffalo Park
46                              New Wanderers Stadium
47                              De Beers Diamond Oval
48                                    OUTsurance Oval
49                                  Brabourne Stadium
50                       Sardar Patel Stadium, Motera
51                                   Barabati Stadium
52       Vidarbha Cricket Association Stadium, Jamtha
53       Himachal Pradesh Cricket Association Stadium
54                                      Nehru Stadium
55                         Subrata Roy Sahara Stadium
56   Shaheed Veer Narayan Singh International Stadium
57                 JSCA International Stadium Complex
58  Maharaja Yadavindra Singh International Cricke...

In [20]:
q('''
SELECT COUNT(DISTINCT TRIM(SUBSTR(venue,1,
CASE WHEN INSTR(venue,',') > 0
THEN INSTR(venue,',')-1 ELSE LENGTH(venue)END))) AS after_rule
FROM matches;
''')

   after_rule
0          42

In [21]:
q('''
SELECT DISTINCT TRIM(SUBSTR(venue,1,
CASE WHEN INSTR(venue,',') > 0
THEN INSTR(venue,',')-1 ELSE LENGTH(venue)END)) AS venue_clean
FROM matches
ORDER BY venue_clean;
''')

                                          venue_clean
0                                Arun Jaitley Stadium
1                                    Barabati Stadium
2                           Barsapara Cricket Stadium
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
4                                   Brabourne Stadium
5                                        Buffalo Park
6                               De Beers Diamond Oval
7                          Dr DY Patil Sports Academy
8   Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
9                 Dubai International Cricket Stadium
10                                       Eden Gardens
11                                   Feroz Shah Kotla
12                                         Green Park
13       Himachal Pradesh Cricket Association Stadium
14                             Holkar Cricket Stadium
15                 JSCA International Stadium Complex
16                                          Kingsmead
17                              M Chinnaswamy Stadium
18                              M.Chinnaswamy Stadium
19                             MA Chidambaram Stadium
20  Maharaja Yadavindra Singh International Cricke...
21            Maharashtra Cricket Association Stadium
22                              Narendra Modi Stadium
23                                      Nehru Stadium
24                              New Wanderers Stadium
25                                           Newlands
26                                    OUTsurance Oval
27       Punjab Cricket Association IS Bindra Stadium
28                 Punjab Cricket Association Stadium
29                 Rajiv Gandhi International Stadium
30                               Sardar Patel Stadium
31             Saurashtra Cricket Association Stadium
32                             Sawai Mansingh Stadium
33   Shaheed Veer Narayan Singh International Stadium
34                            Sharjah Cricket Stadium
35                               Sheikh Zayed Stadium
36                                   St George's Park
37                         Subrata Roy Sahara Stadium
38                                    SuperSport Park
39               Vidarbha Cricket Association Stadium
40                                   Wankhede Stadium
41                              Zayed Cricket Stadium

In [22]:
q('''
SELECT COALESCE (NULL,'unknown');''')

  COALESCE (NULL,'unknown')
0                   unknown

In [23]:
q('''
SELECT city,COALESCE(city,'unknown') AS city_clean
FROM matches
WHERE city IS NULL
LIMIT 10;''')

   city city_clean
0  None    unknown
1  None    unknown
2  None    unknown
3  None    unknown
4  None    unknown
5  None    unknown
6  None    unknown
7  None    unknown
8  None    unknown
9  None    unknown

In [24]:
q('''
SELECT COUNT(*)
FROM matches 
WHERE COALESCE(city,'unknown')='unknown';''')

   COUNT(*)
0        51

In [25]:
q('''
SELECT CAST('2019' AS INTEGER);''')

   CAST('2019' AS INTEGER)
0                     2019

In [26]:
q('''
SELECT DISTINCT season,
SUBSTR(season,1,4)AS first_four,
CAST(SUBSTR(season,1,4)AS INTEGER)AS season_year
FROM matches
ORDER BY season_year;
''')

     season first_four  season_year
0      2008       2008         2008
1      2009       2009         2009
2      2010       2010         2010
3      2011       2011         2011
4      2012       2012         2012
5      2013       2013         2013
6      2014       2014         2014
7      2015       2015         2015
8      2016       2016         2016
9      2017       2017         2017
10     2018       2018         2018
11     2019       2019         2019
12  2020/21       2020         2020
13     2021       2021         2021
14     2022       2022         2022
15     2023       2023         2023
16     2024       2024         2024
17     2025       2025         2025
18     2026       2026         2026

In [27]:
q('''
SELECT COUNT(DISTINCT season),
CAST(SUBSTR(season,1,4) AS INTEGER) AS season_year
FROM matches;''')

   COUNT(DISTINCT season)  season_year
0                      19         2008

In [28]:
q('''
SELECT venue,count(*)
OVER(PARTITION BY venue)
from venues;
''')

,venue,count(*)\nOVER(PARTITION BY venue)
0,Arun Jaitley Stadium,1
1,"Arun Jaitley Stadium, Delhi",1
2,Barabati Stadium,1
3,"Barsapara Cricket Stadium, Guwahati",1
4,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
...,...,...
58,SuperSport Park,1
59,"Vidarbha Cricket Association Stadium, Jamtha",1
60,Wankhede Stadium,1
61,"Wankhede Stadium, Mumbai",1
62,"Zayed Cricket Stadium, Abu Dhabi",1

In [29]:
q('''
SELECT venue_id,venue,
ROW_NUMBER()OVER(PARTITION BY venue ORDER BY venue_id) AS rn 
FROM venues
''')

    venue_id                                              venue  rn
0         16                               Arun Jaitley Stadium   1
1         24                        Arun Jaitley Stadium, Delhi   1
2         55                                   Barabati Stadium   1
3         37                Barsapara Cricket Stadium, Guwahati   1
4         34  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   1
..       ...                                                ...  ..
58        48                                    SuperSport Park   1
59        56       Vidarbha Cricket Association Stadium, Jamtha   1
60         7                                   Wankhede Stadium   1
61        22                           Wankhede Stadium, Mumbai   1
62        25                   Zayed Cricket Stadium, Abu Dhabi   1

[63 rows x 3 columns]

In [30]:
q("""
WITH ranked AS(
SELECT venue_id,venue,
ROW_NUMBER()OVER(PARTITION BY venue ORDER BY venue_id) AS rn
FROM venues)
SELECT COUNT(*) AS kept
FROM ranked
WHERE rn=1;""")

   kept
0    59

In [31]:
con.executescript("""
DROP VIEW IF EXISTS v_matches_clean;

CREATE VIEW v_matches_clean AS
SELECT 
     *,
     CASE
         WHEN venue_comma_clean ='M.Chinnaswamy Stadium' 
         THEN 'M Chinnaswamy Stadium'
         ELSE venue_comma_clean
    END AS venue_clean
FROM (
     SELECT *,
     TRIM(SUBSTR(venue,1,
     CASE WHEN INSTR(venue,',') > 0
     THEN INSTR(venue,',')-1 
     ELSE LENGTH(venue)
     END)) AS venue_comma_clean
    FROM matches
);""")
con.commit()

In [32]:
q('''
SELECT COUNT(DISTINCT venue_clean)
FROM v_matches_clean;
''')

   COUNT(DISTINCT venue_clean)
0                           41

In [33]:
q('''
SELECT venue_clean,COUNT(*) AS matches_hosted
FROM v_matches_clean
GROUP BY venue_clean
ORDER BY matches_hosted DESC
LIMIT 5;
''')

                          venue_clean  matches_hosted
0                    Wankhede Stadium             130
1               M Chinnaswamy Stadium             104
2                        Eden Gardens             104
3              MA Chidambaram Stadium              95
4  Rajiv Gandhi International Stadium              87

In [34]:
q('''
SELECT bowler_type,LENGTH(bowler_type) AS chars,COUNT(*) AS n
FROM deliveries
GROUP BY bowler_type
ORDER BY chars LIMIT 5;
''')

      bowler_type  chars      n
0             NaN    NaN    339
1                    1.0      8
2        Legbreak    8.0  13893
3   Left arm Fast   13.0   3727
4  Right arm Fast   14.0  42126

In [35]:
q('''
SELECT field_pos,LENGTH(field_pos) AS chars,COUNT(*) AS n
FROM players
GROUP BY field_pos
ORDER BY chars LIMIT 5;
''')

          field_pos  chars    n
0               NaN    NaN   88
1                      1.0  612
2      Wicketkeeper   12.0   82
3    Right arm Fast   14.0    1
4  Right arm Medium   16.0    1

In [36]:
con.execute('DROP TABLE IF EXISTS matches_clean')
con.commit()

In [37]:
con.executescript("""
CREATE TABLE matches_clean AS

WITH ranked_venues AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY venue
            ORDER BY venue_id
        ) AS rn
    FROM venues
),

dedup_venues AS (
    SELECT *
    FROM ranked_venues
    WHERE rn = 1
)

SELECT
    m.*,

    COALESCE(
        v.city,
        m.city,
        'UNKNOWN'
    ) AS city_clean,

    CAST(
        SUBSTR(m.season, 1, 4)
        AS INTEGER
    ) AS season_year

FROM v_matches_clean m

LEFT JOIN dedup_venues v
    ON m.venue = v.venue;
""")

con.commit()

In [38]:
q('''SELECT *
FROM matches_clean
LIMIT 5;''')

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id,venue_comma_clean,venue_clean,city_clean,season_year
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,BB McCullum,1,6,1,6,46.0,M Chinnaswamy Stadium,M Chinnaswamy Stadium,Bangalore,2008
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Yuvraj Singh,2,1,1,2,15.0,Rajiv Gandhi International Stadium,Rajiv Gandhi International Stadium,Hyderabad,2017
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,SPD Smith,4,3,4,4,36.0,Maharashtra Cricket Association Stadium,Maharashtra Cricket Association Stadium,Pune,2017
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,CA Lynn,5,6,6,6,57.0,Saurashtra Cricket Association Stadium,Saurashtra Cricket Association Stadium,Rajkot,2017
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,GJ Maxwell,494,4,494,494,71.0,Holkar Cricket Stadium,Holkar Cricket Stadium,Indore,2017

In [39]:
q('''
SELECT 
COUNT(*) AS total_rows,
COUNT(DISTINCT venue_clean) AS cleaned_venues,
COUNT(DISTINCT season_year) AS season_years
FROM matches_clean;''')

   total_rows  cleaned_venues  season_years
0        1212              41            19

In [40]:
d=pd.read_sql('''
SELECT *
FROM deliveries
''',con)

In [41]:
d['fielders_involved'].isna().sum()

np.int64(273886)

find

In [42]:
d.loc[d['fielders_involved'].isna(),'fielders_involved'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: fielders_involved, dtype: str

fix

In [43]:
import ast
d['fielders']=d['fielders_involved'].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else[]
)

In [44]:
d.loc[
    d['fielders_involved']=='[None]',['fielders_involved','fielders']]

       fielders_involved fielders
131               [None]   [None]
138               [None]   [None]
210               [None]   [None]
341               [None]   [None]
385               [None]   [None]
...                  ...      ...
287923            [None]   [None]
287942            [None]   [None]
287979            [None]   [None]
287987            [None]   [None]
288160            [None]   [None]

[3908 rows x 2 columns]

In [45]:
(d['fielders_involved']=='[None]').sum()

np.int64(3908)

none values

##explode

In [46]:
fielders_exploded=d.explode('fielders')

In [47]:
fielders_exploded[
    ['match_id','fielders_involved','fielders']
].dropna(subset=['fielders']).head(10)

     match_id          fielders_involved    fielders
33     335982              ['JH Kallis']   JH Kallis
74     335982                ['P Kumar']     P Kumar
106    335982               ['CL White']    CL White
154    335982               ['M Kartik']    M Kartik
157    335982             ['RT Ponting']  RT Ponting
174    335982               ['M Kartik']    M Kartik
177    335982             ['RT Ponting']  RT Ponting
183    335982                ['WP Saha']     WP Saha
197    335982  ['AB Agarkar', 'WP Saha']  AB Agarkar
197    335982  ['AB Agarkar', 'WP Saha']     WP Saha

In [48]:
fielder_counts=(
    fielders_exploded['fielders']
    .dropna()
    .value_counts()
)
fielder_counts.head(10)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
WP Saha           139
SV Samson         134
RA Jadeja         129
RR Pant           119
SK Raina          119
Name: count, dtype: int64

In [49]:
##BATTING AGGREGATE

batsman total runs

In [50]:
batting=(
d.groupby('batter').agg(runs=('batter_runs','sum'))
   .reset_index())
batting.sort_values('runs',ascending=False).head()

        batter  runs
682    V Kohli  9050
521  RG Sharma  7185
557   S Dhawan  6769
157  DA Warner  6567
308   KL Rahul  5668

In [51]:
d.columns

Index(['season_id', 'match_id', 'batter', 'bowler', 'non_striker',
       'over_number', 'ball_number', 'batter_runs', 'extras', 'total_runs',
       'batsman_type', 'bowler_type', 'player_out', 'fielders_involved',
       'is_wicket', 'is_wide_ball', 'is_no_ball', 'is_leg_bye', 'is_bye',
       'is_penalty', 'wide_ball_runs', 'no_ball_runs', 'leg_bye_runs',
       'bye_runs', 'penalty_runs', 'wicket_kind', 'is_super_over', 'innings',
       'batting_team_id', 'bowling_team_id', 'batting_team', 'bowling_team',
       'fielders'],
      dtype='str')

count of batsman faced legal bowls

In [52]:
legal_balls=(
    d[
        (d['is_wide_ball']==0)&
        (d['is_no_ball']==0)
    ] 
).groupby('batter').size().reset_index(name='legal_balls')

        
    
legal_balls.head(10)

           batter  legal_balls
0  A Ashish Reddy          193
1        A Badoni          815
2      A Chandila            7
3        A Chopra           71
4     A Choudhary           20
5     A Dananjaya            5
6      A Flintoff           53
7        A Kamboj           42
8        A Kumble           47
9       A Manohar          235

In [53]:
batting=batting.merge(
legal_balls,on='batter',how='left')
batting.head()

           batter  runs  legal_balls
0  A Ashish Reddy   280          193
1        A Badoni  1135          815
2      A Chandila     4            7
3        A Chopra    53           71
4     A Choudhary    25           20

In [54]:
batting['strike_rate']=(batting['runs']/batting['legal_balls'])*100
batting.sort_values('runs',ascending=False).head()

        batter  runs  legal_balls  strike_rate
682    V Kohli  9050         6734   134.392634
521  RG Sharma  7185         5399   133.080200
557   S Dhawan  6769         5304   127.620664
157  DA Warner  6567         4680   140.320513
308   KL Rahul  5668         4068   139.331367

In [55]:
d['wicket_kind'].value_counts(dropna=False)

wicket_kind
NaN                      273886
caught                     9056
bowled                     2407
run out                    1176
lbw                         873
caught and bowled           399
stumped                     382
retired hurt                 19
hit wicket                   18
retired out                   6
obstructing the field         4
Name: count, dtype: int64

In [56]:
non_bowler_wicket=[
    'run outs','retired hurt','retired out','obstructing the feild'
]

In [57]:
bowler_wicket_rows=d[
    d['is_wicket']==1&
    ~d['wicket_kind'].isin(non_bowler_wicket)
]

In [58]:
bowling_wickets=(bowler_wicket_rows.groupby('bowler')
                 .size().reset_index(name='wickets')
                 .sort_values('wickets',ascending=False))

bowling_wickets.head()

        bowler  wickets
480  YS Chahal      237
67     B Kumar      230
408  SP Narine      221
114   DJ Bravo      207
188  JJ Bumrah      206

In [59]:
bowler_legal_balls=(
    d[
        (d['is_wide_ball']==0)&
        (d['is_no_ball']==0)
    ] 
).groupby('bowler').size().reset_index(name='legal_balls')

        
    
bowler_legal_balls.head(10)

           bowler  legal_balls
0  A Ashish Reddy          262
1        A Badoni           41
2      A Chandila          234
3     A Choudhary          101
4     A Dananjaya           24
5      A Flintoff           66
6        A Kamboj          355
7        A Kumble          965
8        A Mishra         3371
9        A Mithun          288

misatsken bowler runs

In [60]:
d['bowler_runs']=(d['total_runs']
                  -d['bye_runs']
                  -d['leg_bye_runs']
                  -d['penalty_runs'])

In [61]:
bowler_runs=(d.groupby('bowler')['bowler_runs'].sum().reset_index(name='runs_conceded'))
bowler_runs.head()

           bowler  runs_conceded
0  A Ashish Reddy            396
1        A Badoni             63
2      A Chandila            242
3     A Choudhary            144
4     A Dananjaya             47

In [62]:
bowling =bowler_legal_balls.merge(bowler_runs,on='bowler',how='left')
bowling.head()

           bowler  legal_balls  runs_conceded
0  A Ashish Reddy          262            396
1        A Badoni           41             63
2      A Chandila          234            242
3     A Choudhary          101            144
4     A Dananjaya           24             47

In [63]:
bowling['economy_rate']=bowling['runs_conceded'] /(bowling['legal_balls']/6)

In [64]:
qualified_bowlers= bowling[bowling['legal_balls']>=500]

qualified_bowlers.sort_values('economy_rate',ascending=True).head()

             bowler  legal_balls  runs_conceded  economy_rate
7          A Kumble          965           1058      6.578238
284  M Muralitharan         1528           1706      6.698953
141      DL Vettori          777            879      6.787645
474       SP Narine         4516           5114      6.794508
193         J Botha          694            800      6.916427

In [65]:
q("""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT venue_clean) AS venues,
    COUNT(DISTINCT season_year) AS seasons
FROM matches_clean;
""")

   total_rows  venues  seasons
0        1212      41       19